integration:
  petstore:
    url: http://petStoreUrl
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          schema-generation:
            script:
              append: false
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: update
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
  security:
    oauth2:
      client:
        provider:
          petstore:
            token-uri: http://tokenUrl
        registration:
          petstore:
            client-id: the-client-id
            client-secret: the-client-secret
scheduler:
  pet-scheduler:
    cron: "* * * * * *"
