name: Publish in GitHub Package Registry

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.0.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          with:
          tag_name: ${{  github.ref_name }}
          release_name: ${{  github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
