name: "Call Publish package to the Maven Central Repository"

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:

jobs:
  shared-workflows:
    uses: Sundsvallskommun/.github/.github/workflows/java-maven-publish.yml@main
    secrets: inherit
