name: Publish package to the Maven Central Repository

on:
  workflow_dispatch:

jobs:
  publish:
    env:
      GITHUB_TOKEN: ${{ secrets.UTVECKLINGSFABRIKEN_TOKEN }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.UTVECKLINGSFABRIKEN_TOKEN }}
          fetch-depth: 0

      - name: "Get from tag"
        id: from_tag
        run:
          echo "FROM_TAG=$(git tag --sort=-creatordate | head -1)" >> $GITHUB_OUTPUT

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      - name: Configure Git user and get release version
        run: |
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.name "Utvecklingsfabriken"

      - name: Prepare release with Maven
        env:
          MAVEN_USERNAME: ${"Utvecklingsfabriken"}
          MAVEN_PASSWORD: ${GITHUB_TOKEN}
        run: mvn -B release:prepare

      - name: Perform release with Maven
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        run: mvn -B release:perform -Darguments="-DskipTests"

      - name: "Get latest tag"
        id: latest_tag
        run:
          echo "TO_TAG=$(git tag --sort=-creatordate | head -1)" >> $GITHUB_OUTPUT

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3.7.0
        with:
          fromTag: ${{ steps.from_tag.outputs.FROM_TAG }}
          toTag: ${{ steps.latest_tag.outputs.TO_TAG }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1.1.4
        with:
          tag_name: ${{ steps.latest_tag.outputs.TO_TAG }}
          release_name: ${{ steps.latest_tag.outputs.TO_TAG }}
          body: |
            ## What's Changed
            ${{steps.build_changelog.outputs.changelog}}
            ##
            **Full Changelog**: https://github.com/Sundsvallskommun/dept44/compare/${{ steps.from_tag.outputs.FROM_TAG }}...${{ steps.latest_tag.outputs.TO_TAG }}
          draft: false
          prerelease: false