name: "Call Publish package to the Maven Central Repository"

on:
  workflow_dispatch:

jobs:
  shared-workflows:
    uses: Sundsvallskommun/shared-workflows/.github/workflows/java-maven-publish.yml@main
    secrets: inherit
