name: "Call Java CI with Maven"

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  schedule:
    # At 03:00 on Sunday (Please note: GitHub actions schedule is in UTC time).
    - cron: "0 3 * * 0"

jobs:
  shared-workflows:
    uses: Sundsvallskommun/.github/.github/workflows/java-maven-ci.yml@d3a43f808d780e3a40b2ee698c83966d79b44e76 # main
    with:
      java: "25"
